site_name: Cleantest Framework
nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'Installation': 'user-guide/installation.md'
    - 'Getting Started': 'user-guide/getting-started.md'
  - About:
    - 'License': 'license.md'
theme: readthedocs
