# Copyright 2023 Jason C. Nucciarone
# See LICENSE file for licensing details.

name: cleantest continuous integration checks
on:
  workflow_call:
  pull_request:

jobs:
  inclusive-naming:
    name: Inclusive naming check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true

  lint:
    name: Lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox==4.3.5
      - name: Run linters
        run: tox -e lint

  functional-tests:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install tox==4.3.5
          python3 -m pip install .
          echo "$CHARMCRAFT_AUTH_TOKEN" >> tests/functional/lxd/local/charmhub.secret
          snap download marktext --stable; bash -c "mv marktext_*.snap tests/functional/packages/snap/marktext.snap"
        env:
          CHARMCRAFT_AUTH_TOKEN: ${{ secrets.CHARMCRAFT_AUTH_TOKEN }}
      - name: Setup LXD test environment provider
        uses: canonical/setup-lxd@v0.1.0
        with:
          channel: 5.9/stable
      - name: Run functional tests
        run: tox -e functional
